include: '.test.yml'


"Autovalidate R (autovalidate)":
  extends:
    - .autovalidate-r-autovalidate
  before_script:
    - echo "test1"
  after_script:
    - mkdir test
    - cd test
    - echo "test2" > metadata.yaml
  artifacts:
    when: always
    paths:
      - report.md
      - test/metadata.yaml
    expire_in: 
