
.autovalidate-r-autovalidate:
  stage: build
  script:
    - echo "test" > report.md
  artifacts:
    when: always
    paths:
      - report.md
      - metadata.yaml
    expire_in:  # never


"Autovalidate R (autovalidate)":
  extends:
    - .autovalidate-r-autovalidate
  before_script:
    - echo "test1"
  after_script:
    - echo "test2" > metadata.yaml
  artifacts:
    when: always
    paths:
      - report.md
      - metadata.yaml
    expire_in: 
